# Generated by Django 4.2.1 on 2023-05-20 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TicketSale",
            new_name="Sale",
        ),
    ]
