# Generated by Django 4.2.1 on 2023-05-22 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_type_currency_alter_type_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="total",
        ),
        migrations.RemoveField(
            model_name="type",
            name="tickets_available",
        ),
    ]
